config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  #resources :コントローラ, option(only/except), [:action]
  resources :users, only: [:show, :edit, :update]
  root to: 'top#index'
  resources :groups, only: [:show, :edit, :update]
  resources :questions, only: [:create, :show]
  resources :answers, only: [:new, :create, :edit, :update]

end

app/models/question.rb
class Question < ActiveRecord::Base
  #association
  belongs_to :group
  belongs_to :user
  has_many :answers
  has_one :feed_content, as: :content, dependent: :destroy

  #validation
  validates_presence_of :text, :user_id, :group_id

  #call back
  after_create :create_feed_content


  def user_answer(user_id)
    Answer.find_by(user_id: user_id, question_id: id)
  end

  def answered?(user)
    # レシーバである質問に、現在ログインしているユーザーが既に回答している場合はtrueを、回答していない場合はfalseを返す
    #テーブル名を直接していしてよいのはなぜ？
    answers.exists?(user_id: user.id)
  end

  private
  def create_feed_content
    self.feed_content = FeedContent.create(group_id: group_id, updated_at: updated_at)
  end

end

# find_by method
# user_answerメソッド内部で使用しているfind_byメソッドは、検索条件に該当したレコードを一件だけ取得するメソッドです。
# findメソッドがidのカラムに対してのみ検索をかけられるのに対し、find_byメソッドは検索条件として複数のカラムを指定できるという特徴があります。
# 今回の例でいうとanswersテーブルから user_idカラムの値が、引数として渡されている「現在ログインしているユーザーのid」と一致しかつ、question_idカラムの値が「メソッドを呼び出した元の質問のid」と一致する回答を検索し、取得しています。

# なお「question_id: id」 の id という部分は、self.id の self を省略した形です。

# あるインスタンスメソッド内において、そのインスタンスを利用したインスタンス自身（これをレシーバと言います）を参照する際は self という形で呼び出すことが出来ます。しかしこのselfは省略することも可能なため、今回はメソッドを呼び出した質問の id を whereメソッド の引数に追加する際に「question_id: id」とだけ記述しています。

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  def create
    Question.create(create_params)
    # redirect_to :rootとかくだけではアクション内の処理を全て実行してしまう
    # 慣習的に、redirect_to :root and returnとするほうがよい
    redirect_to :root and return
  end

  def show
    @question = Question.find(params[:id])
    @answers = @question.answers
    
  end

  private
  def create_params
    params.require(:question).permit(:text).merge(user_id: current_user.id, group_id: current_user.group_id)
  end
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/views/questions/_answer.html.erb
<section class="col-md-12">
  <div class="sct_inner">
    <p><%= link_to answer.user.name, user_path(answer.user) %>さんの回答</p>
    <h4>→<%= answer.text %></h4>
  </div>
</section>

app/views/questions/_question.html.erb
<div class="question_content top_content">
  <header class="question_header">
    <div class="question_image icon_image" style="background-image: url(<%= question.user.avatar.url(:medium) %>);"></div>
    <div class="question_user_info user_info">
      <span><%= link_to question.user.name, user_path(question.user) %></span>
      <time><%= time_ago_in_words question.created_at %></time>
    </div>
  </header>
  <div class="question_body">
    <div class="question_box">
      <span class="q">Q</span>
      <span class="question_text"><%= question.text %></span>
    </div>
    
    <div class="questioned">
      <%= link_to "回答#{question.answers.count}件", question_path(question) %>
    </div>
    <% unless question.answers.exists?(user_id: current_user.id) %>
      <%= form_tag(new_answer_path, method: :get, class: "question_submit") do %>
        <%= hidden_field_tag(:question_id, question.id) %>
        <%= submit_tag("回答する") %>
      <% end %>
    <% else %>
      <div class="answer_other">
        <h4>※回答済み※</h4>
      </div>
    <% end %>
  </div>
</div>

<!-- time_ago_in_wordsメソッドについて
投稿時間を「○○時間前」のようにしたい場合に利用するビューヘルパーメソッドです。
特にgemを追加する必要なく利用することができます。デフォルトだと英語なのでrailsの環境設定を日本語で表示したい場合は、config/application.rbの言語設定を日本語（config.i18n.default_locale = :ja）にしておく必要があります。また、日本語の文言表示のためにconfig/locales以下にja.ymlを配置しておきましょう。
 -->

<!-- hidden_field_tagについて
hidden_field_tagは、ユーザーが入力する必要の無い自明のデータをパラメーターとして送信したい時に利用します。
上記では、:question_id というキーに対して個別のquestionのidを値として設定しています。
このことにより、パラメーターが送られた先では、params[:question_id] とするだけで簡単に対応する質問のidを取得することができます。 -->

<!-- exists? / present? / blank? メソッド -->
<!-- .exists? とは、Railsアプリケーションを作成した際にデフォルトで読み込まれる ActiveSupport というgemが実現しているヘルパーメソッドです。メソッドを呼び出したレシーバの中から引数として渡した条件で検索をかけ、データが存在すれば true を、無ければ false を返り値とします。
あくまでもRubyが元々持つ機能では無いので、irb上などでは動作しないことに注意してください。

似たようなメソッドとして .present? や .blank? もあります。こちらは、レシーバが空であるか否かを判別するものです。例えば、以下のように使うことができます。
 -->

 

app/views/questions/show.html.erb
<div class="row form">
  <div class="col-lg-12">
    <h3><span>Q</span><%= @question.text %></h3>
    <div class="group_action panel panel-default">
      <div class="panel-body">
        <% unless @question.answers.exists?(user_id: current_user.id) %>
          <%= link_to '質問に回答する', new_answer_path(question_id: @question.id) %>
        <% else %>
          <h4>※回答済み※</h4>
        <% end %>
      </div>
    </div>
    <% if @question.answers.present? %>
      <h3><span>A</span>この質問への回答</h3>
      <% if @question.answered?(current_user) %>
        <%= render partial: "questions/answer", collection: @answers %>
      <% else %>
        <h1>※質問に答えると他の人の回答を見ることが出来ます</h1>
      <% end %>
    <% end %>
  </div>
</div>